config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get 'panel/index'
resources :productos

 root 'panel#index'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  def index

  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:nombre, :precio, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def nav_link(page, &link_text) 
    class_name = request.env['PATH_INFO'].match(page) ? 'active' : nil

    content_tag(:li, class: class_name) do
      link_to page do
        link_text.call
      end
    end
  end

  def treeview_link(text, &links)
    content = link_to('#') do
      content_tag(:span, text) <<
      content_tag(:i, '', class: "fa pull-right fa-angle-left")
    end

    content << content_tag(:ul, class: 'treeview-menu') do 
      links.call
    end

    content_tag :li, class: 'treeview' do
      content
    end
  end
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/_application_header.html.erb
<header class="header">
  <a href="#" class="logo">
    <!-- Add the class icon to your logo image or logo icon to add the margining -->
    AdminLTE
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <div class="navbar-right">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope"></i>
            <span class="label label-success">4</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 4 messages</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar3.png" class="img-circle" alt="User Image"/>
                    </div>
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li><!-- end message -->
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar2.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      AdminLTE Design Team
                      <small><i class="fa fa-clock-o"></i> 2 hours</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Developers
                      <small><i class="fa fa-clock-o"></i> Today</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar2.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Sales Department
                      <small><i class="fa fa-clock-o"></i> Yesterday</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="pull-left">
                      <img src="/img/avatar.png" class="img-circle" alt="user image"/>
                    </div>
                    <h4>
                      Reviewersz
                      <small><i class="fa fa-clock-o"></i> 2 days</small>
                    </h4>
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user"></i>
            <span>Jane Doe <i class="caret"></i></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header bg-light-blue">
              <img src="/img/avatar3.png" class="img-circle" alt="User Image" />
              <p>
                Jane Doe - Web Developer
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_application_sidebar.html.erb
<section class="sidebar">
  <!-- Sidebar user panel -->
  <div class="user-panel">
    <div class="pull-left image">
      <img src="/img/avatar3.png" class="img-circle" alt="User Image" />
    </div>
    <div class="pull-left info">
      <p>Hello, Jane</p>

      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
  </div>
  <!-- search form -->
  <form action="#" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search..."/>
      <span class="input-group-btn">
        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
    <%= nav_link root_path do %>
      <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    <% end %>
    <%= treeview_link 'Lots of links here' do %>
      <%= nav_link "#" do %>
        <i class="fa fa-angle-double-right"></i>
        One Way
      <% end %>
      <%= nav_link "#" do %>
        <i class="fa fa-angle-double-right"></i>
        Another
      <% end %>
    <% end %>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Vasco::Dashboard</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="skin-blue">

  <%= render "layouts/application_header" %>

  <div class="wrapper row-offcanvas row-offcanvas-left">
    <aside class="left-side sidebar-offcanvas">
      <%= render "layouts/application_sidebar" %>
    </aside>
    <aside class="right-side">
      <%= yield(:content_header) %>

      <% flash.each do |name, msg| %>
        <div class="pad margin no-print">
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= msg %>
          <% end %>
        </div>
      <% end %>

      <%= yield %>
    </aside>
  </div>

  <div class="spinner no-print hidden">
    <img src="/img/ajax-loader.gif" alt="">
  </div>

</body>
</html>

app/views/panel/index.html.erb
<h1>Panel#index</h1>
<p>Find me in app/views/panel/index.html.erb</p>

app/views/productos/_form.html.erb
<section class="content invoice">
  <div class="row">
    <div class="col-md-10">
      <%= form_for(@producto, :html => { :role => "form" }) do |f| %>
        <% if @producto.errors.any? %>
          <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <h4><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h4>

            <ul>
            <% @producto.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

      <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :precio %>
        <%= f.number_field :precio, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :desc %>
        <%= f.text_area :desc, :class => "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</section> 

app/views/productos/edit.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>
      Editando <small><%= link_to productos_path,  @producto %></small>

      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Panel</a></li>
        <li><%= link_to "Productos", productos_path %></li>
        <li class="active">Editar</li>
      </ol>
    </h1>
  </section>
<% end %>

<%= render 'form' %>

app/views/productos/index.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Listing <small>productos</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">productos</li>
    </ol>    
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to new_producto_path(@producto), :class => 'btn btn-success' do %>
              <span class="glyphicon glyphicon-plus"></span>
              Nuevo Producto
            <% end %>          
          </div>
        </div>
        <div class="box-body table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
              <th>Nombre</th>
              <th>Precio</th>
              <th>Descripción</th>
                            <th></th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= content_tag_for(:tr, @productos) do |producto| %>
              <td><%= producto.nombre %></td>
              <td><%= producto.precio %></td>
              <td><%= producto.desc %></td>
                            <td><%= link_to 'Show', producto %></td>
                <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
                <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: '¿Seguro?' } %></td>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/productos/new.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>New <small>producto</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "productos", productos_path %></li>
      <li class="active">New</li>
    </ol>
  </section>
<% end %>

<%= render 'form' %>

app/views/productos/show.html.erb
<% content_for :content_header  do %>
  <section class="content-header">
    <h1>Show <small>producto</small></h1>

    <ol class="breadcrumb">
      <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><%= link_to "Productos", productos_path %></li>
      <li class="active">Show</li>
    </ol>
  </section>
<% end %>

<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header">
          <div class="box-tools pull-right">
            <%= link_to edit_producto_path(@producto), :class => 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
            <% end %>          
          </div>
        </div>
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Nombre:</dt>
            <dd><%= @producto.nombre %></dd>

            <dt>Precio:</dt>
            <dd><%= @producto.precio %></dd>

            <dt>Desc:</dt>
            <dd><%= @producto.desc %></dd>

          </dl>
        </div>
      </div>
    </div>
  </div>
</section>